### ISSUE TITLE
基于mathcad的杨氏模量数据处理

### ISSUE THREAD

**Issue by EmptyKB** [HITSZ-OpenAuto/PHYS1002A#7]
[杨氏模量.zip](https://github.com/HITSZ-OpenAuto/PHYS1002A/files/13310359/default.zip)
如题，只需修改的部分为数据&A类不确定度。
以下是需修改部分的截图：
![image](https://github.com/HITSZ-OpenAuto/PHYS1002A/assets/145801275/c4ec9e56-3756-459a-997a-181a5e4c5502)
![image](https://github.com/HITSZ-OpenAuto/PHYS1002A/assets/145801275/7a5a9acc-c0d4-4335-8ede-4121444d1029)
以下是结果截图：
![image](https://github.com/HITSZ-OpenAuto/PHYS1002A/assets/145801275/fcffcfff-cd0d-4440-a64b-be843f543cea)

**Comment by longlin10086** [comment]
文件不大的话不需要打包成zip文件，直接将你的文件夹放在对应目录下后提交pr即可
